/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedRouteRouteImport } from './routes/_authed/route'
import { Route as AcceptInviteRouteImport } from './routes/accept-invite'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as AuthedCouriersIndexRouteImport } from './routes/_authed/couriers/index'
import { Route as AuthedCouriersNewRouteImport } from './routes/_authed/couriers/new'
import { Route as AuthedIntegrationsIndexRouteImport } from './routes/_authed/integrations/index'
import { Route as AuthedMethodsIndexRouteImport } from './routes/_authed/methods/index'
import { Route as AuthedOrdersIndexRouteImport } from './routes/_authed/orders/index'
import { Route as AuthedOrdersReferenceRouteImport } from './routes/_authed/orders/$reference'
import { Route as AuthedOrdersImportRouteImport } from './routes/_authed/orders/import'
import { Route as AuthedOrdersNewRouteImport } from './routes/_authed/orders/new'
import { Route as AuthedOrdersSimpleRouteImport } from './routes/_authed/orders/simple'
import { Route as AuthedProblemsIndexRouteImport } from './routes/_authed/problems/index'
import { Route as AuthedProductsIndexRouteImport } from './routes/_authed/products/index'
import { Route as AuthedReturnsIndexRouteImport } from './routes/_authed/returns/index'
import { Route as AuthedSettingsIndexRouteImport } from './routes/_authed/settings/index'

const AuthedRouteRoute = AuthedRouteRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInviteRoute = AcceptInviteRouteImport.update({
  id: '/accept-invite',
  path: '/accept-invite',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedCouriersIndexRoute = AuthedCouriersIndexRouteImport.update({
  id: '/couriers/',
  path: '/couriers/',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedCouriersNewRoute = AuthedCouriersNewRouteImport.update({
  id: '/couriers/new',
  path: '/couriers/new',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedIntegrationsIndexRoute = AuthedIntegrationsIndexRouteImport.update({
  id: '/integrations/',
  path: '/integrations/',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedMethodsIndexRoute = AuthedMethodsIndexRouteImport.update({
  id: '/methods/',
  path: '/methods/',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedOrdersIndexRoute = AuthedOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedOrdersReferenceRoute = AuthedOrdersReferenceRouteImport.update({
  id: '/orders/$reference',
  path: '/orders/$reference',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedOrdersImportRoute = AuthedOrdersImportRouteImport.update({
  id: '/orders/import',
  path: '/orders/import',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedOrdersNewRoute = AuthedOrdersNewRouteImport.update({
  id: '/orders/new',
  path: '/orders/new',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedOrdersSimpleRoute = AuthedOrdersSimpleRouteImport.update({
  id: '/orders/simple',
  path: '/orders/simple',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedProblemsIndexRoute = AuthedProblemsIndexRouteImport.update({
  id: '/problems/',
  path: '/problems/',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedProductsIndexRoute = AuthedProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedReturnsIndexRoute = AuthedReturnsIndexRouteImport.update({
  id: '/returns/',
  path: '/returns/',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedSettingsIndexRoute = AuthedSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AuthedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/couriers/new': typeof AuthedCouriersNewRoute
  '/orders/$reference': typeof AuthedOrdersReferenceRoute
  '/orders/import': typeof AuthedOrdersImportRoute
  '/orders/new': typeof AuthedOrdersNewRoute
  '/orders/simple': typeof AuthedOrdersSimpleRoute
  '/couriers/': typeof AuthedCouriersIndexRoute
  '/integrations/': typeof AuthedIntegrationsIndexRoute
  '/methods/': typeof AuthedMethodsIndexRoute
  '/orders/': typeof AuthedOrdersIndexRoute
  '/problems/': typeof AuthedProblemsIndexRoute
  '/products/': typeof AuthedProductsIndexRoute
  '/returns/': typeof AuthedReturnsIndexRoute
  '/settings/': typeof AuthedSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/accept-invite': typeof AcceptInviteRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/': typeof AuthedIndexRoute
  '/couriers/new': typeof AuthedCouriersNewRoute
  '/orders/$reference': typeof AuthedOrdersReferenceRoute
  '/orders/import': typeof AuthedOrdersImportRoute
  '/orders/new': typeof AuthedOrdersNewRoute
  '/orders/simple': typeof AuthedOrdersSimpleRoute
  '/couriers': typeof AuthedCouriersIndexRoute
  '/integrations': typeof AuthedIntegrationsIndexRoute
  '/methods': typeof AuthedMethodsIndexRoute
  '/orders': typeof AuthedOrdersIndexRoute
  '/problems': typeof AuthedProblemsIndexRoute
  '/products': typeof AuthedProductsIndexRoute
  '/returns': typeof AuthedReturnsIndexRoute
  '/settings': typeof AuthedSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteRouteWithChildren
  '/accept-invite': typeof AcceptInviteRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/_authed/': typeof AuthedIndexRoute
  '/_authed/couriers/new': typeof AuthedCouriersNewRoute
  '/_authed/orders/$reference': typeof AuthedOrdersReferenceRoute
  '/_authed/orders/import': typeof AuthedOrdersImportRoute
  '/_authed/orders/new': typeof AuthedOrdersNewRoute
  '/_authed/orders/simple': typeof AuthedOrdersSimpleRoute
  '/_authed/couriers/': typeof AuthedCouriersIndexRoute
  '/_authed/integrations/': typeof AuthedIntegrationsIndexRoute
  '/_authed/methods/': typeof AuthedMethodsIndexRoute
  '/_authed/orders/': typeof AuthedOrdersIndexRoute
  '/_authed/problems/': typeof AuthedProblemsIndexRoute
  '/_authed/products/': typeof AuthedProductsIndexRoute
  '/_authed/returns/': typeof AuthedReturnsIndexRoute
  '/_authed/settings/': typeof AuthedSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accept-invite'
    | '/forgot-password'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/couriers/new'
    | '/orders/$reference'
    | '/orders/import'
    | '/orders/new'
    | '/orders/simple'
    | '/couriers/'
    | '/integrations/'
    | '/methods/'
    | '/orders/'
    | '/problems/'
    | '/products/'
    | '/returns/'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/accept-invite'
    | '/forgot-password'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/'
    | '/couriers/new'
    | '/orders/$reference'
    | '/orders/import'
    | '/orders/new'
    | '/orders/simple'
    | '/couriers'
    | '/integrations'
    | '/methods'
    | '/orders'
    | '/problems'
    | '/products'
    | '/returns'
    | '/settings'
  id:
    | '__root__'
    | '/_authed'
    | '/accept-invite'
    | '/forgot-password'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/_authed/'
    | '/_authed/couriers/new'
    | '/_authed/orders/$reference'
    | '/_authed/orders/import'
    | '/_authed/orders/new'
    | '/_authed/orders/simple'
    | '/_authed/couriers/'
    | '/_authed/integrations/'
    | '/_authed/methods/'
    | '/_authed/orders/'
    | '/_authed/problems/'
    | '/_authed/products/'
    | '/_authed/returns/'
    | '/_authed/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRouteRoute: typeof AuthedRouteRouteWithChildren
  AcceptInviteRoute: typeof AcceptInviteRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invite': {
      id: '/accept-invite'
      path: '/accept-invite'
      fullPath: '/accept-invite'
      preLoaderRoute: typeof AcceptInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/couriers/': {
      id: '/_authed/couriers/'
      path: '/couriers'
      fullPath: '/couriers/'
      preLoaderRoute: typeof AuthedCouriersIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/couriers/new': {
      id: '/_authed/couriers/new'
      path: '/couriers/new'
      fullPath: '/couriers/new'
      preLoaderRoute: typeof AuthedCouriersNewRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/integrations/': {
      id: '/_authed/integrations/'
      path: '/integrations'
      fullPath: '/integrations/'
      preLoaderRoute: typeof AuthedIntegrationsIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/methods/': {
      id: '/_authed/methods/'
      path: '/methods'
      fullPath: '/methods/'
      preLoaderRoute: typeof AuthedMethodsIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/orders/': {
      id: '/_authed/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof AuthedOrdersIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/orders/$reference': {
      id: '/_authed/orders/$reference'
      path: '/orders/$reference'
      fullPath: '/orders/$reference'
      preLoaderRoute: typeof AuthedOrdersReferenceRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/orders/import': {
      id: '/_authed/orders/import'
      path: '/orders/import'
      fullPath: '/orders/import'
      preLoaderRoute: typeof AuthedOrdersImportRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/orders/new': {
      id: '/_authed/orders/new'
      path: '/orders/new'
      fullPath: '/orders/new'
      preLoaderRoute: typeof AuthedOrdersNewRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/orders/simple': {
      id: '/_authed/orders/simple'
      path: '/orders/simple'
      fullPath: '/orders/simple'
      preLoaderRoute: typeof AuthedOrdersSimpleRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/problems/': {
      id: '/_authed/problems/'
      path: '/problems'
      fullPath: '/problems/'
      preLoaderRoute: typeof AuthedProblemsIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/products/': {
      id: '/_authed/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof AuthedProductsIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/returns/': {
      id: '/_authed/returns/'
      path: '/returns'
      fullPath: '/returns/'
      preLoaderRoute: typeof AuthedReturnsIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/settings/': {
      id: '/_authed/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthedSettingsIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
  }
}

interface AuthedRouteRouteChildren {
  AuthedIndexRoute: typeof AuthedIndexRoute
  AuthedCouriersNewRoute: typeof AuthedCouriersNewRoute
  AuthedOrdersReferenceRoute: typeof AuthedOrdersReferenceRoute
  AuthedOrdersImportRoute: typeof AuthedOrdersImportRoute
  AuthedOrdersNewRoute: typeof AuthedOrdersNewRoute
  AuthedOrdersSimpleRoute: typeof AuthedOrdersSimpleRoute
  AuthedCouriersIndexRoute: typeof AuthedCouriersIndexRoute
  AuthedIntegrationsIndexRoute: typeof AuthedIntegrationsIndexRoute
  AuthedMethodsIndexRoute: typeof AuthedMethodsIndexRoute
  AuthedOrdersIndexRoute: typeof AuthedOrdersIndexRoute
  AuthedProblemsIndexRoute: typeof AuthedProblemsIndexRoute
  AuthedProductsIndexRoute: typeof AuthedProductsIndexRoute
  AuthedReturnsIndexRoute: typeof AuthedReturnsIndexRoute
  AuthedSettingsIndexRoute: typeof AuthedSettingsIndexRoute
}

const AuthedRouteRouteChildren: AuthedRouteRouteChildren = {
  AuthedIndexRoute: AuthedIndexRoute,
  AuthedCouriersNewRoute: AuthedCouriersNewRoute,
  AuthedOrdersReferenceRoute: AuthedOrdersReferenceRoute,
  AuthedOrdersImportRoute: AuthedOrdersImportRoute,
  AuthedOrdersNewRoute: AuthedOrdersNewRoute,
  AuthedOrdersSimpleRoute: AuthedOrdersSimpleRoute,
  AuthedCouriersIndexRoute: AuthedCouriersIndexRoute,
  AuthedIntegrationsIndexRoute: AuthedIntegrationsIndexRoute,
  AuthedMethodsIndexRoute: AuthedMethodsIndexRoute,
  AuthedOrdersIndexRoute: AuthedOrdersIndexRoute,
  AuthedProblemsIndexRoute: AuthedProblemsIndexRoute,
  AuthedProductsIndexRoute: AuthedProductsIndexRoute,
  AuthedReturnsIndexRoute: AuthedReturnsIndexRoute,
  AuthedSettingsIndexRoute: AuthedSettingsIndexRoute,
}

const AuthedRouteRouteWithChildren = AuthedRouteRoute._addFileChildren(
  AuthedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthedRouteRoute: AuthedRouteRouteWithChildren,
  AcceptInviteRoute: AcceptInviteRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
