/**
 * Built-in profile: Royal Mail Pro Shipping API (Royal Mail API Shipping V3 REST, api.royalmail.net/shipping/v3).
 * For Royal Mail account (OBA) customers. Written from the public client documentation for the
 * v3 REST API (September 2026): POST /token exchanges the IBM client id/secret plus the RMG
 * security username/password for a token valid about 4 hours, sent as X-RMG-Auth-Token; POST
 * /shipments creates and (with shipmentAction Process) labels in one call, returning base64 label
 * images; PUT /shipments/{id}/printLabel reprints; PUT /shipments/cancel voids.
 * VERIFY at first test: the token reply field name ("token" assumed), the customsInformation
 * field names, and your account's service codes (customer mapped codes are allowed).
 */
import type { BuiltinProfile } from './index.js';

export const royalMailProShipping: BuiltinProfile = {
  key: 'royal-mail-pro-shipping',
  name: 'Royal Mail (Pro Shipping API)',
  credentialSchema: [
    { key: 'clientId', label: 'API client id (X-IBM-Client-Id)', required: true, help: 'From your application on developer.royalmail.net' },
    { key: 'clientSecret', label: 'API client secret', secret: true, required: true },
    { key: 'username', label: 'Shipping API username', required: true, help: 'The Pro Shipping / OBA API user name (X-RMG-Security-Username)' },
    { key: 'password', label: 'Shipping API password', secret: true, required: true },
    { key: 'postingLocation', label: 'Posting location (10 digits)', help: 'Optional if your account has only one posting location' },
    { key: 'department', label: 'OBA department code (10 digits, optional)' },
  ],
  services: [
    { code: 'TPN', name: 'Tracked 24', tracked: true, maxTransitDays: 1, domestic: true, limits: { maxWeightKg: 20 } },
    { code: 'TPS', name: 'Tracked 48', tracked: true, maxTransitDays: 2, domestic: true, limits: { maxWeightKg: 20 } },
    { code: 'TPM', name: 'Tracked 24 with signature', tracked: true, signature: true, maxTransitDays: 1, domestic: true },
    { code: 'TPL', name: 'Tracked 48 with signature', tracked: true, signature: true, maxTransitDays: 2, domestic: true },
    { code: 'SD1', name: 'Special Delivery Guaranteed by 1pm', tracked: true, signature: true, express: true, maxTransitDays: 1, domestic: true },
    { code: 'CRL1', name: '1st Class (account)', tracked: false, maxTransitDays: 1, domestic: true, limits: { maxWeightKg: 20 } },
    { code: 'CRL2', name: '2nd Class (account)', tracked: false, maxTransitDays: 3, domestic: true, limits: { maxWeightKg: 20 } },
    { code: 'BPL1', name: '1st Class Large Letter', tracked: false, maxTransitDays: 1, domestic: true, limits: { maxWeightKg: 0.75, maxThinnestCm: 2.5 } },
    { code: 'BPL2', name: '2nd Class Large Letter', tracked: false, maxTransitDays: 3, domestic: true, limits: { maxWeightKg: 0.75, maxThinnestCm: 2.5 } },
    { code: 'MTA', name: 'International Tracked', tracked: true, maxTransitDays: 7, international: true },
    { code: 'MTB', name: 'International Tracked & Signed', tracked: true, signature: true, maxTransitDays: 7, international: true },
    { code: 'OLA', name: 'International Standard (untracked)', tracked: false, maxTransitDays: 10, international: true },
  ],
  definition: {
    version: 1,
    baseUrl: 'https://api.royalmail.net/shipping/v3',
    timeoutMs: 30_000,
    rateLimitPerMinute: 300,
    headers: { 'X-IBM-Client-Id': '{{ cred.clientId }}', 'X-IBM-Client-Secret': '{{ cred.clientSecret }}' },
    auth: {
      kind: 'login',
      request: { method: 'POST', path: '/token', contentType: 'none', responseType: 'json', headers: { 'X-RMG-Security-Username': '{{ cred.username }}', 'X-RMG-Security-Password': '{{ cred.password }}' }, errorPath: 'message' },
      tokenPath: 'token',
      header: 'X-RMG-Auth-Token',
      prefix: '',
      ttlMinutes: 230,
      retryOn401: true,
    },
    accountFields: ['postingLocation', 'department'],
    notes: 'Account (OBA) customers only. The token lasts about 4 hours and is refreshed automatically. Service codes may be Royal Mail system codes (TPN, TPS, SD1 …) or the customer-mapped codes set up in your account. VERIFY at first test: token reply field, customsInformation names, service codes.',
    operations: {
      auth_test: { method: 'GET', path: '/addresses', responseType: 'json', errorPath: 'message' },
      create_shipment: {
        method: 'POST',
        path: '/shipments',
        body: {
          shipper: {
            shipperReference: '{{ shipment.reference | truncate:20 }}',
            'shipperReference2?': '{{ order.customerName | truncate:20 }}',
            'shipperDepartment?': '{{ cred.department }}',
            'companyName?': '{{ warehouse.company | truncate:35 }}',
            contactName: '{{ warehouse.contactName | default:warehouse.company | truncate:35 }}',
            addressLine1: '{{ warehouse.line1 | truncate:35 }}',
            'addressLine2?': '{{ warehouse.line2 | truncate:35 }}',
            town: '{{ warehouse.city | truncate:35 }}',
            'county?': '{{ warehouse.region | truncate:35 }}',
            countryCode: '{{ warehouse.country }}',
            postcode: '{{ warehouse.postCode | truncate:10 }}',
            'phoneNumber?': '{{ warehouse.phone | digits | truncate:20 }}',
            'emailAddress?': '{{ warehouse.email }}',
            'vatNumber?': '{{ warehouse.vatNumber }}',
          },
          destination: {
            'companyName?': '{{ order.company | truncate:35 }}',
            contactName: '{{ order.contactName | truncate:35 }}',
            addressLine1: '{{ order.line1 | truncate:35 }}',
            'addressLine2?': '{{ order.line2 | truncate:35 }}',
            town: '{{ order.city | truncate:35 }}',
            'county?': '{{ order.region | truncate:35 }}',
            countryCode: '{{ order.country }}',
            'postcode?': '{{ order.postCode | truncate:10 }}',
            'phoneNumber?': '{{ order.phone | digits | truncate:20 }}',
            'emailAddress?': '{{ order.email }}',
          },
          shipmentInformation: {
            shipmentDate: '{{ now | date:YYYY-MM-DD }}',
            serviceCode: '{{ method.serviceCode }}',
            serviceOptions: {
              'postingLocation?': '{{ cred.postingLocation }}',
              serviceFormat: 'P',
              'recordedSignedFor?': { $includeIf: 'order.signature', $if: 'order.signature', then: true },
              'trackingNotifications?': { $includeIf: 'order.email', $if: 'order.email', then: 'Email' },
            },
            totalPackages: '{{ parcels | length }}',
            totalWeight: '{{ totalWeightKg | round:3 }}',
            weightUnitOfMeasure: 'KG',
            product: 'NDX',
            'descriptionOfGoods?': { $includeIf: 'order.international', $if: 'order.international', then: '{{ order.description | truncate:70 }}' },
            'reasonForExport?': { $includeIf: 'order.international', $if: 'order.international', then: 'Sale of goods' },
            'value?': { $includeIf: 'order.international', $if: 'order.international', then: '{{ order.goodsValue | round:2 }}' },
            'currency?': { $includeIf: 'order.international', $if: 'order.international', then: '{{ order.currency }}' },
            'incoterms?': { $includeIf: 'order.international', $if: 'order.international', then: '{{ order.incoterm }}' },
            labelFormat: 'PDF',
            shipmentAction: 'Process',
            packages: {
              $map: 'parcels',
              as: 'p',
              item: { packageOccurrence: '{{ p.position }}', weight: '{{ p.weightKg | round:3 }}', length: '{{ p.lengthCm | round:1 }}', width: '{{ p.widthCm | round:1 }}', height: '{{ p.heightCm | round:1 }}' },
            },
            'items?': {
              $includeIf: 'order.international',
              $map: 'order.lines',
              as: 'line',
              item: {
                quantity: '{{ line.quantity | int }}',
                description: '{{ line.customsDescription | default:line.name | truncate:70 }}',
                value: '{{ line.unitValue | round:2 }}',
                'weight?': '{{ line.weightKg | round:3 }}',
                'hsCode?': '{{ line.hsCode | digits }}',
                'skuCode?': '{{ line.sku | truncate:30 }}',
                'countryOfOrigin?': '{{ line.countryOfOrigin }}',
              },
            },
          },
          'customsInformation?': {
            $includeIf: 'order.international',
            'preRegistrationNumber?': '{{ warehouse.iossNumber }}',
            'preRegistrationType?': { $includeIf: 'warehouse.iossNumber', $if: 'warehouse.iossNumber', then: 'IOSS' },
            'shippersEori?': '{{ warehouse.eori }}',
          },
        },
        successWhen: { path: 'packages[0].uniqueId' },
        errorPath: 'errors[0].errorDescription',
        response: {
          courierReference: 'packages[0].uniqueId',
          trackingNumber: 'packages[0].trackingNumber',
          trackingUrl: 'packages[0].trackingUrl',
          labelBase64: 'labelImages',
          parcels: { path: 'packages', trackingNumber: 'trackingNumber' },
        },
      },
      get_label: {
        method: 'PUT',
        path: '/shipments/{{ shipment.courierReference }}/printLabel',
        body: { labelFormat: 'PDF' },
        responseType: 'json',
        errorPath: 'errors[0].errorDescription',
      },
      void_shipment: {
        method: 'PUT',
        path: '/shipments/cancel',
        body: [{ shipmentId: '{{ shipment.courierReference }}', reasonForCancellation: 'Cancelled in Smooth Parcel' }],
        errorPath: 'errors[0].errorDescription',
      },
      track: {
        method: 'GET',
        path: 'https://api.royalmail.net/mailpieces/v2/{{ shipment.trackingNumber }}/events',
        headers: { 'X-Accept-RMG-Terms': 'yes' },
        responseType: 'json',
        errorPath: 'errors[0].errorDescription',
        response: { events: 'mailPieces.events', status: 'eventName', time: 'eventDateTime', location: 'locationName', description: 'eventName' },
      },
    },
    label: { format: 'pdf', source: 'inline', nativeSize: '6x4', base64Path: 'labelImage' },
    trackingUrlTemplate: 'https://www.royalmail.com/track-your-item#/tracking-results/{{ shipment.trackingNumber }}',
    statusMap: [
      { match: 'Item received*', status: 'SHIPPED' },
      { match: 'Accepted at*', status: 'SHIPPED' },
      { match: 'Collected*', status: 'SHIPPED' },
      { match: 'Item despatched*', status: 'IN_TRANSIT' },
      { match: 'Item leaving*', status: 'IN_TRANSIT' },
      { match: 'Item at*', status: 'IN_TRANSIT' },
      { match: 'In transit*', status: 'IN_TRANSIT' },
      { match: 'Out for delivery*', status: 'IN_TRANSIT' },
      { match: 'Delivered*', status: 'DELIVERED' },
      { match: 'Delivery attempted*', status: 'PROBLEM', problem: 'delivery_failed' },
      { match: 'Item returned*', status: 'PROBLEM', problem: 'returning' },
      { match: 'Return to sender*', status: 'PROBLEM', problem: 'returning' },
      { match: 're:customs|held|duty', status: 'PROBLEM', problem: 'held' },
      { match: 're:damaged|lost', status: 'PROBLEM', problem: 'damaged_lost' },
    ],
    retryOn: [429, 502, 503, 504],
  },
};
